apiVersion: v1
kind: Service
metadata:
  name: engine
spec:
  selector:
    app: engine
  ports:
    - port: 3000
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: engine
  template:
    metadata:
      labels:
        app: engine
    spec:
      containers:
        - name: engine
          image: common:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: config
          imagePullPolicy: IfNotPresent
          command: ["node"]
          args: ["/home/node/app/engine/dist/index.js"]
