apiVersion: v1
kind: Service
metadata:
  name: scheduler
spec:
  selector:
    app: scheduler
  ports:
    - port: 3002
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scheduler
  template:
    metadata:
      labels:
        app: scheduler
    spec:
      containers:
        - name: scheduler
          image: common:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
              name: config
          imagePullPolicy: Always
          command: ["node"]
          args: ["/usr/src/app/scheduler/dist/index.js"]
