apiVersion: v1
kind: Service
metadata:
  name: logic
spec:
  selector:
    app: logic
  ports:
    - port: 3001
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logic
  template:
    metadata:
      labels:
        app: logic
    spec:
      containers:
        - name: logic
          image: common:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: config
          imagePullPolicy: IfNotPresent
          command: ["node"]
          args: ["/home/node/app/logic/dist/index.js"]
      initContainers:
        - name: postgres
          image: postgres:13.4
          imagePullPolicy: "IfNotPresent"
          command: ["/bin/sh", "-c", "pg_isready -h postgres -p 5432 && echo $?"]
